services:
  portfolio-nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network
    depends_on:
      - portfolio-php

  portfolio-php:
    image: php:8.2-fpm
    container_name: portfolio-php
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - proxy-network
    depends_on:
      - portfolio-db

  portfolio-db:
    image: mariadb:10.6
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ezechiel
      MYSQL_DATABASE: portfeuil
      MYSQL_USER: user_portfolio
      MYSQL_PASSWORD: ezechiel
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
