error_log /dev/stdout info;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    sendfile on;
    access_log /dev/stdout;

    server {
        listen 8080;
        
        root /app/dist;
        index index.html;

        # Fichiers statiques et SPA
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Assets Vite (CSS, JS, images)
        location /assets/ {
            try_files $uri =404;
        }

        # Fichiers PHP depuis /app/public
        location ~ ^/(traitment|config)\.php$ {
            root /app/public;
            try_files $uri =404;
            
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Bloquer l'accès aux fichiers sensibles
        location ~ /\.(git|env) {
            deny all;
        }
    }
}